//
//  SourceModel.swift
//  RealEyes_CodingChallenge
//
//  Created by Oniel Rosario on 8/21/19.
//  Copyright © 2019 Oniel Rosario. All rights reserved.
//

import Foundation

protocol SourceModeling {
    var sources: [VideoClip] { get }
}

class Source: SourceModeling {
    lazy var sources: [VideoClip] = [
        VideoClip(link: URL(string:"https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "videoStillFrame1", ofType: "png")!), name: "Parkour"),
        VideoClip(link: URL(string: "https://abclive1-lh.akamaihd.net/i/abc_live05@423399/master.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "ABCNews", ofType: "jpg")!), name: "ABC News Live Coverage"),
        VideoClip(link: URL(string: "https://adultswimhls-i.akamaihd.net/hls/live/238460/adultswim/main/1/master.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "adultSwim", ofType: "jpg")!), name: "Adult Swim"),
        VideoClip(link: URL(string: "https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_3.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "rickAndMorty", ofType: "png")!), name: "Rick & Morty"),
        VideoClip(link: URL(string: "https://liveprodeuwest.akamaized.net/eu1/Channel-EUTVqvs-AWS-ireland-1/Source-EUTVqvs-1000-1_live.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "BloombergTV", ofType: "png")!), name: "Bloomberg TV"),
        VideoClip(link: URL(string: "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1567120691/ei/0whoXdOpFM_zigTfxCU/ip/71.218.140.12/id/hHW1oY26kxQ.348/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r6---sn-qxoedn7z.googlevideo.com/playlist_type/DVR/initcwndbps/7530/mm/44/mn/sn-qxoedn7z/ms/lva/mv/m/mvi/5/pl/15/dover/11/keepalive/yes/mt/1567098980/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,playlist_type/sig/ALgxI2wwRQIhAIuytR0_0xYJ-RvgR-IwT4VWmlq03zO-wjOX_x-DsXrpAiBAjtQqlUBQpzYxhId4vigxL0R_GLj7gukm7xFy2Dg1Og%3D%3D/lsparams/hls_chunk_host,initcwndbps,mm,mn,ms,mv,mvi,pl/lsig/AHylml4wRAIgBeBknxPNNXlkONqg8173NvM1ok3a6KzrV6ZJlpK6xfACICrGmSfKABm-Tk7hTYn6hlZjsmSHae4u0CcurW0SHsMo/playlist/index.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "lowfiradio", ofType: "png")!), name: "Lo-Fi Radio"),
        VideoClip(link: URL(string: "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1567121120/ei/gApoXaH_A4CFir4PocCR4AE/ip/71.218.140.12/id/21X5lGlDOfg.1/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r5---sn-qxoedn7k.googlevideo.com/playlist_type/DVR/initcwndbps/7630/mm/44/mn/sn-qxoedn7k/ms/lva/mv/m/mvi/4/pl/15/dover/11/keepalive/yes/mt/1567099406/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,playlist_type/sig/ALgxI2wwRQIgeo97qWnL3TzqVrF1NpQzWbrlSSIlQ7Fb35Wl7lVdNU4CIQD6plS5dDvrnrdLPVJO-Vyuj8aYDbAWZeT0fLM-Gy27hw%3D%3D/lsparams/hls_chunk_host,initcwndbps,mm,mn,ms,mv,mvi,pl/lsig/AHylml4wRQIhALRp0EnAcGRORk-jr8zr1kfquGyHqbKgqHk7GraUG1oVAiARxL8hgTJ_sAdw2SeXhpGVZx45SRTePre8oF13C7so-w%3D%3D/playlist/index.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "nasa", ofType: "jpg")!), name: "NASA TV"),
        VideoClip(link: URL(string: "https://r3---sn-qxo7rn7s.googlevideo.com/videoplayback?expire=1567098115&ei=o7BnXaCIKcTMD9baoIgD&ip=71.218.140.12&id=o-ACtd3qzMtEAXJB4IRVGXWJhdotAQGjsJGy2ndZqpoytX&itag=135&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-qxo7rn7s%2Csn-qxoedn7e&ms=au%2Crdu&mv=m&mvi=2&pl=15&initcwndbps=845000&mime=video%2Fmp4&gir=yes&clen=352689506&dur=4657.499&lmt=1565757234391443&mt=1567076423&fvip=3&keepalive=yes&c=WEB&txp=7316222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgI6hOofI1j8SaOnjnWfRdkWAFxLRZbwv2lWEuVXVWzNACIF9R5bPSq0rS6qqPKSaRmxlRUq9myTXKScxES-ayxV3Y&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAJyXqIIytog7nLqGv40DOe4NDzHsCZ9qVAecKdSpCRwUAiEA6axqzm2--XHcLQDeSP9oGanlHQQ8WlrX-E7B_co3aGk%3D&ratebypass=yes")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "Simpsons", ofType: "jpg")!), name: "Simpsons Marathon"),
        VideoClip(link: URL(string: "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1567098732/ei/DLNnXeqKHc_zigS-1qCABQ/ip/71.218.140.12/id/vNCWiEhSjF4.0/itag/94/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D135/hls_chunk_host/r5---sn-qxoedn7d.googlevideo.com/playlist_type/DVR/initcwndbps/6380/mm/44/mn/sn-qxoedn7d/ms/lva/mv/m/mvi/4/pl/15/dover/11/keepalive/yes/mt/1567077031/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,playlist_type/sig/ALgxI2wwRQIhALGEBWwmWbtIeJ8cF0OY1EOSq4UFsQ9uTcnZ0y4WzYdcAiAZ8mqPrcnr6MW4E2UFI0gXWM6_x_dDFia_jrl8eZTGUg%3D%3D/lsparams/hls_chunk_host,initcwndbps,mm,mn,ms,mv,mvi,pl/lsig/AHylml4wRgIhAJ-R9kAY3wWK-pHWyB8Lu2VZqrKtgpE3UGeHCds_JbcOAiEAzLBO1l8exliTjUHelN8cndFTjo_OsiMBJFwwrzo2mYk%3D/playlist/index.m3u8")!, thumbNail: URL(fileURLWithPath: Bundle.main.path(forResource: "heroes", ofType: "jpg")!), name: "Dragon Ball Heroes")
    ]
}
